### ISSUE TITLE
Current Tutorials on CodeProject doesnt work

### ISSUE THREAD

**Issue by jasonmbrown** [mika76/MyDownloader#2]
The tutorials for MyDownloader that are on Code Project don't work right now. It would be nice to get few new Examples of doing things with this well made library.

**Comment by mika76** [comment]
Hey @jasonmbrown I didn't really write the tool, just posted the code on github so I could play with it, but never really got around to it.

**Comment by mika76** [comment]
Actually it seems he put it on github himself at https://github.com/guilhermelabigalini/mydownloader so maybe you should ask there...
